### ISSUE TITLE
Issues with Advanced Systems Manager

### ISSUE THREAD

**Issue by meradudd** [Vaygrim/vcs3#10]
I have noticed a couple of issues with this mod.  

The first is that, whenever you break any of the blocks of the mod, they turn into systems cable (SFM 'inventory cable').  If you use a wrench, however, they are turned into items properly.

Secondly, it appears that the 'specify amount' feature doesn't function properly (i.e. setting a condition to check for 32 gold ore will return true if it sees one gold ore or a stack.)

I've looked on the mod github and it appears that neither of these are reported issues. Don't know if it's the pack, the mod or what.

I'm a HUGE fan of SFM and ASM has great promise as it's follow-on.  Difference is that SFM works and ASM....not-so-much.

**Comment by Vaygrim** [comment]
This is something that really should be posted on the issue tracker for ASM. We can't actually do anything about this issue.

**Comment by meradudd** [comment]
Reported to mod author.
