### ISSUE TITLE
Request for when the pack updates

### ISSUE THREAD

**Issue by meradudd** [Vaygrim/vcs3#12]
Not EXACTLY sure if this is the right place, but.....

When the next pack update occurs, I would request a revert from ASM back to Steve's Factory Manager.  ASM has great promise, but the mod is presently quite bugged and limited compared to SFM and the mod author has disappeared since mid-October (a few days before the latest fix).

Barring a reversion to SFM, mayhap pulling ASM all together until a functional version is available.

Thank you for your time and, most especially, the work which has gone into making a really interesting and enjoyable modpack.

Pax,

Mer

**Comment by Greylocke** [comment]
ASM will be pulled from the pack at the next release, likely to happen at the beginning of February.

Thank you for your feedback -- glad you are enjoying the pack!
