### ISSUE TITLE
There are several shovels that do not allow you to dig "agricraft" water pads

### ISSUE THREAD

**Issue by astrutzenberg-godaddy** [Vaygrim/vcs3#2]
Specifically these are the blocks that are used to grow the water artichokes in witchery.

I was able to get a repro using the mekanism tool's "steel shovel", and based off a conversation with another player this may also extend to the periodot shovel as well?

Repro Steps:
1) Create a vanilla iron shovel
2) Create a vanilla based hoe
3) till some land with the hoe to turn it into farmland
4) using the steel shovel, right click on the farmland

Results:  Nothing happens :D

5) using the iron shovel, right click on the farmland

Results:  It generates the empty water pad

Expected results: either tool should work.with this scenario

**Comment by RedeyeTheGoblin** [comment]
Unfortunately not something that can be changed via config files or MineTweaker, you'll need to report this directly to the mod author.
