### ISSUE TITLE
[Enhance] Add some additional magical crops "expansion' recipes to make marble, limestone, granite, andesite and diorite

### ISSUE THREAD

**Issue by mahldcat** [Vaygrim/vcs3#20]
Most of the tier 1 blocks are generated via a 2x2 grid recipe using nature blocks.

My thinking were what if we were to add some "expansion" recipes (you expand your inventory at the expense of earth essence)

These would be 3x3 recipes...
I'm basing this off the Agricraft.zs  script?  (not sure if I got the syntax correct or not.....but something like:

recipes.addShaped(**item to craft**  \* 64,
[[magicalcrops:EarthSeeds, magicalcrops:EarthSeeds, magicalcrops:EarthSeeds],
 [magicalcrops:EarthSeeds, **item to craft**, magicalcrops:EarthSeeds],
 [magicalcrops:EarthSeeds, magicalcrops:EarthSeeds, magicalcrops:EarthSeeds]]);

**Comment by Greylocke** [comment]
This has been added to my fork. Should be merged in the next couple days.
Added shaped 2x2 essence-based recipes for Andesite, Diorite, Granite, Limestone, Marble. Also Packed Ice. Cuz it's cool. See what I did there?
