### ISSUE TITLE
Bronze Paxel

### ISSUE THREAD

**Issue by therealericbj** [Vaygrim/vcs3#23]
Do you already have a means in place to get Mekanism Bronze?

Everyone that I can find seems to default to Thermal Foundation Bronze.

Also, is there a way to get the Mekanism version of a Bronze tool?  The Bronze Paxel recipe seems to only like the Mekanism tools.

I am using version the 1.2 version of the pack.

**Comment by RedeyeTheGoblin** [comment]
Mekanism bronze tools were made uncraftable in version 1.2 - we wanted to have a single type of tool for each metal and decided to go with the Thermal Foundation tools.

Thermal Foundation bronze and Mekanism bronze should be ore dictionaried so you can use either in recipes - if you find any that are not, please let us know.
