### ISSUE TITLE
infusion altar stabilizers and the arcane abacus

### ISSUE THREAD

**Issue by meradudd** [Vaygrim/vcs3#36]
There are a number of blocks (from cobblestone to ancient diamond blocks) which state that they can be used as an infusion stabilizer in the tool-tip, but the arcane abacus ignores them when calculating altar stability.  I do not have confirmation that those blocks do or do not contribute to infusion altar stability, but either the tool-tips should be changed or they should be added to the abacus' white-list.

**Comment by Vaygrim** [comment]
I have been using SOME of those stabilizer blocks, and they work just fine for me. That being said I've interacted with maybe, less than 5% of all of them. So it wouldn't surprise me if some are bugged. I think the bigger issue you might be seeing here is that the Arcane Abacus only deals in 'whole numbers' for a stabilization value.. while some of these stabilization blocks only contribute a fractional value (Example: +0.01 stabilization). The end result you see is the Arcane Abacus either 'rounding' the final value, or just truncating the 'extra' decimal values on the end.

The only real way to test this is to get some of your 'broken blocks' and use ABSURD amounts of them within every single air gap block around an Infusion Altar that you possibly could, even to the point of inconvenience. Then check your stabilization, see what happens. If it is STILL not affecting things, we'll just have to talk to the respective mod authors adding those stabilizer notes as we cannot change the tooltips nor add things to the Arcane Abacus's check list.

**Comment by meradudd** [comment]
The rounding thing doesn't bug me.  The reason I noticed this is that the abacus will say "stabilizer at x,y,z doesn't have a match"....but when I have an un-matched block of the sort which is tool-tipped (just tried adding a full stack of cobblestone), it neither tells me there's an unmatched pair OR alters the stability numbers.  A stack of unmatched pairs should reduce the overall stability by 6 or so, but the abacus didn't budge.  Thus, I _think_ the abacus doesn't know that the other blocks matter.

I'll see about a test-world build where I'm _trying_ for instability and let ya know.

**Comment by Vaygrim** [comment]
Thanks! I'm curious what your testing yields!

**Comment by meradudd** [comment]
OK....preliminary testing complete.  Took a stability 90 altar and replaced @400 crystals and skulls with  a mixture of cobble, netherrack, ancient 'xx' blocks and slabs, gold-etched obsidian, mossy cobble and crystal blocks and slabs in various patterns such that if any one were not valid stabilizers, it would throw the whole stability off.  Abacus said "Overall instability 13"  Ran multiple 'Dangerous' infusions (including delaying one by 15 seconds in error due to insufficient essentia).  Not a whiff of taint, zot from the altar or anything knocked off the pedestals.

The blocks which I didn't test are the garden stuff lanterns, the anvils from Thaumium bases or the thauminite, salis mundis or quicksilver blocks from Thaumic Bases.

I know that the 'standard' infusion stabilizers are 'airy' blocks.  You can't place anything on the crystal blocks (redstone, torches, etc)....but you CAN on the crystal slabs and the other blocks tested that the abacus won't consider valid stabilizers.

I would argue that, barring further testing, that the abacus has a white-list of 'airy blocks' which includes crystal blocks (but not slabs) from Thaumic Bases, but not the other blocks from that mod OR recognizing the non-mod infusion stabilizers.

Hopefully that helps.

**Comment by meradudd** [comment]
I've been doing further testing and it appears that the items labeled as infusion stabilizers are, in fact, what they say on the tin.  Therefore, I'll consider the matter closed with the post-script to ask Blusunrize to consider tweaking the way the Abacus looks for valid stabilizer blocks.  Thanks again for a wonderful modpack, guys.
