### ISSUE TITLE
Tardis Crash VC3-1.1 ATLauncher (Taking off, Drifting)

### ISSUE THREAD

**Issue by LobsterEmbodiment** [Vaygrim/vcs3#6]
There appears to be an issue with the Tardis mod and the Laboratory block. Whenever I attempt to take off with the Laboratory in the Tardis the game crashes to Desktop, while I have reported this bug to the developer I have yet to hear from them regarding it. This has also happened in VC3-1.0

Crash Report is Attached in case you want to relay the issue to the Developer.

Thanks in advance.

[crash-2015-12-16_17.16.41-server.txt](https://github.com/Vaygrim/vcs3/files/64230/crash-2015-12-16_17.16.41-server.txt)

**Comment by RedeyeTheGoblin** [comment]
Yeah we're aware of the issue however nothing we can do on our end unfortunately (Other than say "Don't try to craft stuff when drifting").

I'm keeping an eye on the mod so when a fix is introduced it'll be rolled into an update.

**Comment by RedeyeTheGoblin** [comment]
This should be resolved in v1.2 with the darkcore rollback - if it still occurs, please re-open!
