### ISSUE TITLE
tardis crash 

### ISSUE THREAD

**Issue by highlandpiper10** [Vaygrim/vcs3#9]
apparently drifting while not changing the destination causes a crash and world corruption.

i tried it twice and lost my world both times.

I checked the tardis site and it is an issue that they only fixed by rolling back to dark core .78 the one in the pack is apparently unstable.

https://github.com/DarkholmeTenk/TardisModIssues/issues/342

**Comment by RedeyeTheGoblin** [comment]
Known fault, will be resolved in VC3-1.2.
